---
control:
  hosts:
    vagrant:
      ansible_connection: local
      ansible_user: vagrant
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: 10.0.3.40
    ubuntu2:
      ansible_host: 10.0.3.58
  vars:
    ansible_user: packt
    ansible_become: true
    ansible_become_pass: password
centos:
  hosts:
    centos1:
      ansible_host: 10.0.3.178
      ansible_port: 2222
    centos2:
      ansible_host: 10.0.3.87
  vars:
    ansible_user: root
...
